SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY,
       SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK AS A
JOIN AUTHOR AS B
JOIN BOOK_SALES AS C
ON A.AUTHOR_ID = B.AUTHOR_ID AND A.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;