WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS (
    SELECT ECOLI_DATA.ID
    FROM ECOLI_DATA
    JOIN FIRST_GEN ON ECOLI_DATA.PARENT_ID = FIRST_GEN.ID
),
THIRD_GEN AS (
    SELECT ECOLI_DATA.ID
    FROM ECOLI_DATA
    JOIN SECOND_GEN ON ECOLI_DATA.PARENT_ID = SECOND_GEN.ID
)
SELECT ID
FROM THIRD_GEN
ORDER BY ID;